server:
  resources:
    limits:
      cpu: 2
      memory: "12Gi"
    requests:
      cpu: 2
      memory: "8Gi"

  storage:
    main:
      storageClassName: "longhorn-nvme"

    backups:
      nfs:
        server: 192.168.1.135
        path: /mnt/data/backups/palworld

  image:
    repository: ghcr.io/usa-reddragon/palworld-server
    tag: main@sha256:2a616f293d6f76b62ef65423dd86611c5591fb2dfbd4372b17805969ef67bfe4

  config:
    rcon:
      externalPassword:
        name: palworld-passwords
        key: rconPassword
    community:
      externalPassword:
        name: palworld-passwords
        key: communityPassword

    server_name: "Dragon_Palworld_Server"
    timezone: "America/Chicago"
    public_ip: "palworld.mcswain.dev"
    public_port: "8211"
    server_description: "USA-RedDragon's Palworld Server"

    daily_reboot:
      enable: true
      time: "0 10 * * *"

    env:
      DAYTIME_SPEEDRATE: "1.000000"
      NIGHTTIME_SPEEDRATE: "1.000000"
      EXP_RATE: "2.500000"
      PAL_CAPTURE_RATE: "1.000000"
      PAL_SPAWN_NUM_RATE: "1.500000"
      PAL_DAMAGE_RATE_ATTACK: "1.000000"
      PAL_DAMAGE_RATE_DEFENSE: "1.000000"
      PLAYER_DAMAGE_RATE_ATTACK: "1.000000"
      PLAYER_DAMAGE_RATE_DEFENSE: "1.000000"
      PLAYER_STOMACH_DECREASE_RATE: "1.000000"
      PLAYER_STAMINA_DECREASE_RATE: "0.500000"
      PLAYER_AUTO_HP_REGEN_RATE: "1.000000"
      PLAYER_AUTO_HP_REGEN_RATE_IN_SLEEP: "1.000000"
      PAL_STOMACH_DECREASE_RATE: "1.000000"
      PAL_STAMINA_DECREASE_RATE: "0.7500000"
      PAL_AUTO_HP_REGEN_RATE: "1.000000"
      PAL_AUTO_HP_REGEN_RATE_IN_SLEEP: "1.000000"
      BUILD_OBJECT_DAMAGE_RATE: "1.000000"
      BUILD_OBJECT_DETERIORATION_DAMAGE_RATE: "1.000000"
      COLLECTION_DROP_RATE: "1.000000"
      COLLECTION_OBJECT_HP_RATE: "1.000000"
      COLLECTION_OBJECT_RESPAWN_SPEED_RATE: "1.000000"
      ENEMY_DROP_ITEM_RATE: "1.000000"
      DEATH_PENALTY: "None"
      ENABLE_PLAYER_TO_PLAYER_DAMAGE: "false"
      ENABLE_FRIENDLY_FIRE: "false"
      ENABLE_INVADER_ENEMY: "true"
      ACTIVE_UNKO: "true"
      ENABLE_AIM_ASSIST_PAD: "true"
      ENABLE_AIM_ASSIST_KEYBOARD: "false"
      DROP_ITEM_MAX_NUM: "3000"
      DROP_ITEM_MAX_NUM_UNKO: "1000"
      BASE_CAMP_MAX_NUM: "128"
      BASE_CAMP_WORKER_MAX_NUM: "15"
      DROP_ITEM_ALIVE_MAX_HOURS: "1.000000"
      AUTO_RESET_GUILD_NO_ONLINE_PLAYERS: "false"
      AUTO_RESET_GUILD_TIME_NO_ONLINE_PLAYERS: "72.000000"
      GUILD_PLAYER_MAX_NUM: "3"
      PAL_EGG_DEFAULT_HATCHING_TIME: "28.000000"
      WORK_SPEED_RATE: "1.000000"
      IS_MULTIPLAY: "false"
      IS_PVP: "false"
      CAN_PICKUP_OTHER_GUILD_DEATH_PENALTY_DROP: "false"
      ENABLE_NON_LOGIN_PENALTY: "false"
      ENABLE_FAST_TRAVEL: "true"
      IS_START_LOCATION_SELECT_BY_MAP: "true"
      EXIST_PLAYER_AFTER_LOGOUT: "false"
      ENABLE_DEFENSE_OTHER_GUILD_PLAYER: "false"
      COOP_PLAYER_MAX_NUM: "4"
      REGION: "USA"
      USEAUTH: "true"
      BAN_LIST_URL: "https://api.palworldgame.com/api/banlist.txt"
      DISABLE_GENERATE_SETTINGS: "false"
      BACKUP_CRON_EXPRESSION: '*/5 * * * *'
      DELETE_OLD_BACKUPS: "true"
      OLD_BACKUP_DAYS: '7'
