apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: symmetricds
resources:
  - helm.yaml
configMapGenerator:
  - name: symmetricds-chart-values
    files:
      - values.yaml=values.yaml
configurations:
  - kustomizeconfig.yaml
