apiVersion: cilium.io/v2
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: public-gateway
spec:
  endpointSelector:
    matchLabels:
      policy.mcswain.dev/public-gateway: "true"
  ingress:
    - fromEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: envoy-gateway-system
            gateway.envoyproxy.io/owning-gateway-name: public
            gateway.envoyproxy.io/owning-gateway-namespace: envoy-gateway-system
