apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: astro-processing
resources:
  - helm.yaml
configMapGenerator:
  - name: pixinsight-worker-chart-values
    files:
      - values.yaml=values.yaml
configurations:
  - kustomizeconfig.yaml
