apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dump978
resources:
  - ns.yaml
  - helm.yaml
  - prom.yaml
configMapGenerator:
  - name: chart-values
    files:
      - values.yaml=values.yaml
configurations:
  - kustomizeconfig.yaml
