apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: frigate
resources:
  - helm.yaml
  - backends.yaml
  - forward-auth.yaml
configMapGenerator:
  - name: frigate-chart-values
    files:
      - values.yaml=values.yaml
configurations:
  - kustomizeconfig.yaml
