apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: rmfakecloud
resources:
  - helm.yaml
  - cert.yaml
configMapGenerator:
  - name: chart-values
    files:
      - values.yaml=values.yaml
configurations:
  - kustomizeconfig.yaml
