apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: intel-device-plugin
resources:
  - helm.yaml
configMapGenerator:
  - name: chart-values
    files:
      - values.yaml=values.yaml
  - name: chart-values-gpu
    files:
      - values.yaml=gpu-values.yaml
configurations:
  - kustomizeconfig.yaml
