operatorConfig:
  image:
    repository: jacob.pub/ghcr.io/tailscale/k8s-operator
    tag: v1.90.9@sha256:af6d1206e61b4edca752329efca36d7867efc1e6529207b5217980786403d753
  hostname: "tailscale-operator"

  resources: {}

proxyConfig:
  image:
    repository: jacob.pub/ghcr.io/tailscale/tailscale
    tag: v1.90.9@sha256:9975353aae933e8fbd1a81226d092a9225b9a0f98b173d365a9d525eca1cc298

apiServerProxyConfig:
  mode: "noauth"

imagePullSecrets:
- name: registry-zot
