operatorConfig:
  image:
    repository: jacob.pub/ghcr.io/tailscale/k8s-operator
    tag: v1.94.2@sha256:7956bd50dca9dc804b98720df94d112b54af85449ed0bf8cc7fad0346b225067
  hostname: "tailscale-operator"

  resources: {}

proxyConfig:
  image:
    repository: jacob.pub/ghcr.io/tailscale/tailscale
    tag: v1.94.2@sha256:95e528798bebe75f39b10e74e7051cf51188ee615934f232ba7ad06a3390ffa1

apiServerProxyConfig:
  mode: "noauth"

imagePullSecrets:
- name: registry-zot
