operatorConfig:
  image:
    repository: jacob.pub/ghcr.io/tailscale/k8s-operator
    tag: v1.90.9
  hostname: "tailscale-operator"

  resources: {}

proxyConfig:
  image:
    repository: jacob.pub/ghcr.io/tailscale/tailscale
    tag: v1.92.3@sha256:00e029e54305d8d8112db38ceb8817389aefb0d337d428605bf34058f06a971c

apiServerProxyConfig:
  mode: "noauth"

imagePullSecrets:
- name: registry-zot
