operatorConfig:
  image:
    repository: jacob.pub/ghcr.io/tailscale/k8s-operator
    tag: v1.92.3@sha256:aadcfa559912721fda402f73527328b6e0f0e7cfaac864a679c8c500375543df
  hostname: "tailscale-operator"

  resources: {}

proxyConfig:
  image:
    repository: jacob.pub/ghcr.io/tailscale/tailscale
    tag: v1.92.4@sha256:d6734d69fd7d31b1861589e347463954aa6097f9a61aa4f8f763ba94bfe0e5b9

apiServerProxyConfig:
  mode: "noauth"

imagePullSecrets:
- name: registry-zot
