operatorConfig:
  image:
    repository: jacob.pub/ghcr.io/tailscale/k8s-operator
    tag: v1.92.5@sha256:551e085388ca94cf86fe42eecf9a6250ac59f597b05ef98dfbb205219af7746d
  hostname: "tailscale-operator"

  resources: {}

proxyConfig:
  image:
    repository: jacob.pub/ghcr.io/tailscale/tailscale
    tag: v1.90.9@sha256:9975353aae933e8fbd1a81226d092a9225b9a0f98b173d365a9d525eca1cc298

apiServerProxyConfig:
  mode: "noauth"

imagePullSecrets:
- name: registry-zot
