operatorConfig:
  image:
    repository: jacob.pub/ghcr.io/tailscale/k8s-operator
    tag: v1.94.1@sha256:a5fe08cf8fcc2b53382e33f26147bd1088c6db945fce7c45928a48c89adbde30
  hostname: "tailscale-operator"

  resources: {}

proxyConfig:
  image:
    repository: jacob.pub/ghcr.io/tailscale/tailscale
    tag: v1.94.1@sha256:21df0b5a84efa35c0a507f4dd2340e1b1295683634a28968707354d5bd991d9c

apiServerProxyConfig:
  mode: "noauth"

imagePullSecrets:
- name: registry-zot
