replicaCount: 2

operator:
  image:
    repository: jacob.pub/docker.io/hashicorp/hcp-terraform-operator
    tag: "2.10.0"

  syncPeriod: 1h

  tfeAddress: "https://tfe.mcswain.dev"

kubeRbacProxy:
  image:
    repository: jacob.pub/quay.io/brancz/kube-rbac-proxy
    tag: v0.20.0

controllers:
  agentPool:
    workers: 1
    syncPeriod: 30s
  module:
    workers: 1
    syncPeriod: 5m
  project:
    workers: 1
    syncPeriod: 5m
  workspace:
    workers: 1
    syncPeriod: 5m
