replicaCount: 2

operator:
  image:
    repository: jacob.pub/docker.io/hashicorp/hcp-terraform-operator
    tag: "2.11.3@sha256:fb812a7ce1720bcdd88ae45658329a8141fedf4ff9477663782a9a1fb2c5beea"

  syncPeriod: 1h

  tfeAddress: "https://tfe.mcswain.dev"

  env:
    TF_LOG_OPERATOR: debug

kubeRbacProxy:
  image:
    repository: jacob.pub/quay.io/brancz/kube-rbac-proxy
    tag: v0.20.2@sha256:ad0fa9f0adc928b557663297bd22c610533960d77acdec289ce8a636f0ea2114

controllers:
  agentPool:
    workers: 1
    syncPeriod: 30s
  module:
    workers: 1
    syncPeriod: 5m
  project:
    workers: 1
    syncPeriod: 5m
  workspace:
    workers: 1
    syncPeriod: 5m
