apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: openspeedtest
resources:
  - helm.yaml
configMapGenerator:
  - name: openspeedtest-chart-values
    files:
      - values.yaml=values.yaml
configurations:
  - kustomizeconfig.yaml
