apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cert-manager
resources:
  - clusterissuer.yaml
  - dmrhub.cert.yaml
  - jacob.network.cert.yaml
  - jacob.pub.cert.yaml
  - kubewg.net.cert.yaml
  - mcswain.cloud.cert.yaml
  - mcswain.dev.cert.yaml
  - mcswain.photography.cert.yaml
  - mcswain.wiki.cert.yaml
  - thisspacedoesnotexist.com.cert.yaml
