apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: cloudflare
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
  name: s3
  namespace: minio
spec:
  ingressClassName: nginx
  rules:
  - host: s3.mcswain.dev
    http:
      paths:
      - backend:
          service:
            name: minio-app
            port:
              number: 9000
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - s3.mcswain.dev
    secretName: s3-mcswain-dev-tls
